name: Release drafter

on:
  push:
    branches: [main, test-wf]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_secrets:
    name: Check secrets
    runs-on: ubuntu-latest
    outputs:
      PAT: ${{ steps.pat.outputs.is_set }}
      ALL: ${{ steps.pat.outputs.is_set }}
    steps:
    -
      name: Check PAT
      id: pat
      run: |
        echo "is_set: ${{ secrets.PAT != '' }}"
        echo "::set-output name=is_set::${{ secrets.PAT != '' }}"
  update_release_draft:
    name: Update draft release
    runs-on: ubuntu-latest
    needs:
    - check_secrets
    steps:
    -
      if: ${{ needs.check_secrets.outputs.PAT == 'true' }}
      name: Draft next release
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
